version: "3.8"
services:

  celery_admin:
    build: .
    restart: unless-stopped
    entrypoint: celery -A main worker -l info
    env_file:
      - .env
    networks:
      - ksenia-chat-bot
    depends_on:
      - redis_admin
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1G

  redis_admin:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - ksenia-chat-bot
    volumes:
      - redis-data:/data
#    deploy:
#      resources:
#        limits:
#          memory: 512M

  admin:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - static-files:/home/app/static
      - media-files:/home/app/media
    networks:
      - ksenia-chat-bot
    ports:
    - "8001:8001"
 #   deploy:
 #     resources:
 #       limits:
 #         cpus: '1'
 #         memory: 1G

volumes:
  static-files:
  media-files:
  redis-data:

networks:
  ksenia-chat-bot:
    external:
      name: ksenia-chat-bot