version: "3.8"
services:

  admin:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - static-files:/home/app/static
      - media-files:/home/app/media
    networks:
      - ksenia-chat-bot
    ports:
    - "8001:8001"

volumes:
  static-files:
  media-files:
  redis-data:

networks:
  ksenia-chat-bot:
    external:
      name: ksenia-chat-bot