version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media  # Добавляем том для медиафайлов
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./.env.local

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
    command: celery -A KseniyaChatBotAdmin worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ./.env.local

  celery_beat:
    build:
      context: .
    command: celery -A KseniyaChatBotAdmin beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ./.env.local

volumes:
  static_volume:
  media_volume:

networks:
  ksenia-chat-bot:
    external:
      name: ksenia-chat-bot