version: "3.8"
services:

  celery_admin:
    build: .
    restart: unless-stopped
    entrypoint: celery -A main worker -l info
    env_file:
      - .env
    networks:
      - bot_default
    depends_on:
      - redis_admin
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1G

  redis_admin:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - bot_default
    volumes:
      - redis-data:/data
#    deploy:
#      resources:
#        limits:
#          memory: 512M

  admin:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - static-files:/home/app/static
      - media-files:/home/app/media
    networks:
      - bot_default
    ports:
    - "8001:8001"
 #   deploy:
 #     resources:
 #       limits:
 #         cpus: '1'
 #         memory: 1G

volumes:
  static-files:
  media-files:
  redis-data:

networks:
  bot_default:
    external: true
#  bot_tg-ksenya-chat-bot:
#    name: bot_tg-ksenya-chat-bot
#    external: true
#  tg-ksenya-chat-bot:
#    name: tg-ksenya-chat-bot_default
#    external: true
