# Generated by Django 4.2.16 on 2024-09-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255, verbose_name='Номер счета')),
                ('field1', models.CharField(max_length=255, verbose_name='поле 1')),
                ('field2', models.CharField(max_length=255, verbose_name='поле 2')),
            ],
            options={
                'db_table': 'rbdetails',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, verbose_name='Номер чека')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплата заказа')),
                ('paid_at', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('EU', 'EU'), ('RB', 'RB')], max_length=20)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgusers.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
