# Generated by Django 5.1.1 on 2024-09-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tgusers', '0002_alter_telegramuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255, verbose_name='')),
                ('field2', models.CharField(max_length=255, verbose_name='')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgusers.telegramuser')),
            ],
        ),
    ]
