# Generated by Django 5.1.1 on 2024-09-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='Скриншот оплаты'),
        ),
    ]
