# Generated by Django 5.1.1 on 2024-09-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rbpaymentdetails'),
        ('tgusers', '0002_alter_telegramuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbpaymentdetails',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgusers.telegramuser', verbose_name='Пользователь'),
        ),
    ]
