# Generated by Django 5.1.1 on 2024-09-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_rbpaymentdetails_account_id'),
        ('tgusers', '0002_alter_telegramuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgusers.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='rbpaymentdetails',
            name='field1',
            field=models.CharField(max_length=255, verbose_name='поле 1'),
        ),
        migrations.AlterField(
            model_name='rbpaymentdetails',
            name='field2',
            field=models.CharField(max_length=255, verbose_name='поле 2'),
        ),
    ]
