# Generated by Django 5.1.1 on 2024-09-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_screenshot',
        ),
    ]
