# Generated by Django 5.1.1 on 2024-09-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Ник пользователя')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия пользователя')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('is_blocked', models.BooleanField()),
                ('role', models.CharField(choices=[('CLIENT', 'Клиент'), ('MANAGER', 'Менеджер')], max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
