# Generated by Django 5.1.1 on 2024-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_blocked', models.BooleanField()),
                ('role', models.CharField(choices=[('CLIENT', 'Клиент'), ('MANAGER', 'Менеджер')], max_length=20)),
            ],
        ),
    ]
