# Generated by Django 5.1.1 on 2024-09-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
