# Generated by Django 5.1.1 on 2024-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='user',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(default=1, max_length=30, verbose_name='Ник пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('MANAGER', 'Менеджер')], max_length=20, verbose_name='Роль'),
        ),
    ]
