# Generated by Django 5.1.1 on 2025-04-08 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startmessage',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'ТГ Пользователь', 'verbose_name_plural': 'ТГ Пользователи'},
        ),
        migrations.RenameField(
            model_name='startmessage',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='is_blocked',
            new_name='is_bot_blocked',
        ),
        migrations.RemoveField(
            model_name='startmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='startmessage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='startmessage',
            name='type',
            field=models.CharField(
                choices=[('GREETER', 'Приветствие'), ('AFTER_SUBSCRIBE', 'После Подписки')],
                default='GREETER',
                max_length=255,
                unique=True,
                verbose_name='Тип'
            ),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='policy_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвердил Политику Конф'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name='Номер Телефона'
            ),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.CharField(max_length=255, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Никейм'),
        ),
        migrations.AlterModelTable(
            name='startmessage',
            table='startmessage',
        ),
        migrations.CreateModel(
            name='ButtonMessage',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('type', models.CharField(
                    choices=[('INLINE', 'Inline')],
                    max_length=10,
                    verbose_name='Тип'
                )),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('callback_data', models.CharField(
                    blank=True,
                    max_length=255,
                    null=True,
                    verbose_name='Callback Data'
                )),
                ('message', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='buttons',
                    to='tgusers.startmessage',
                    verbose_name='Сообщение'
                )),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
                'db_table': 'buttonmessage',
            },
        ),
    ]
