# Generated by Django 5.1.1 on 2024-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgusers', '0002_startmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='startmessage',
            name='start_message',
            field=models.CharField(default=1, max_length=255, verbose_name='Начальное сообщение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startmessage',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
