# Generated by Django 5.1.1 on 2024-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgusers', '0003_startmessage_start_message_alter_startmessage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startmessage',
            name='start_message',
        ),
        migrations.AddField(
            model_name='startmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='startmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
