# Generated by Django 5.1.1 on 2024-09-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя канала')),
                ('url', models.URLField(verbose_name='Ссылка на канал')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
