# Generated by Django 4.2.16 on 2024-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя канала')),
                ('url', models.URLField(verbose_name='Ссылка на канал')),
                ('eur_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма в Евро')),
                ('rub_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма в Рублях')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channel',
            },
        ),
    ]
