# Generated by Django 5.1.1 on 2024-09-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='amount',
        ),
        migrations.AddField(
            model_name='channel',
            name='eur_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество для Евросоюза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='rub_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество для Республики Беларусь'),
            preserve_default=False,
        ),
    ]
