# Generated by Django 5.1.1 on 2024-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя канала'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.URLField(verbose_name='Ссылка на канал'),
        ),
    ]
