# Generated by Django 5.1.1 on 2025-04-08 14:15

import apps.notifications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgusers', '0002_alter_startmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('image', models.ImageField(
                    blank=True,
                    null=True,
                    upload_to=apps.notifications.models.Notification.upload_to,
                    verbose_name='Изображение'
                )),
                ('file', models.FileField(
                    blank=True,
                    null=True,
                    upload_to=apps.notifications.models.Notification.upload_to,
                    verbose_name='Файл'
                )),
                ('text', models.TextField(verbose_name='Текст')),
                ('send_separately',
                models.BooleanField(default=False, verbose_name='Отправить в отдельности')),
                ('send_all', models.BooleanField(default=False, verbose_name='Отправить всем')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Уведомление для Пользователя',
                'verbose_name_plural': 'Уведомления для Пользователей',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='UsersNotifications',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('delivered', models.BooleanField(default=False, verbose_name='Доставлено')),
                ('delivered_time',
                models.DateTimeField(null=True, verbose_name='Доставлено (дата)')),
                ('notification', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='users_notifications',
                    to='notifications.notification'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='users_notifications',
                    to='tgusers.telegramuser'
                )),
            ],
            options={
                'db_table': 'usersnotifications',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(
                related_name='notifications',
                through='notifications.UsersNotifications',
                to='tgusers.telegramuser',
                verbose_name='ТГ Пользователи'
            ),
        ),
    ]
